# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI and CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    name: Build
    
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build image
      run: docker build -t mevlutgur/denex-api .

    - name: Push to Docker Hub 
      run: docker push mevlutgur/denex-api

  deploy:

    name: Deploy

    needs: build

    runs-on: ubuntu-latest

    steps:
          
    - name: Start Mongo Container and Pull - Start Api Container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          echo "Starting the deployment"
          docker volume create denex-data
          docker network inspect denex-net >/dev/null 2>&1 || \
          docker network create denex-net
          docker start mongodb-service ||  docker run  -d -v  denex-data:/data/db    -p 27018:27017  --network=denex-net     --name=mongodb-service  mongo
          docker logout
          docker login -u=${{ secrets.DOCKER_USERNAME }} -p=${{ secrets.DOCKER_PASSWORD }}
          docker pull mevlutgur/denex-api
          docker logout
          docker rm -f denex-service
          docker run -d -p 3003:80 --network=denex-net --name=denex-service mevlutgur/denex-api